### ISSUE TITLE
Use time.process_time for benchmarks

### ISSUE THREAD

**Issue by jeromekelleher** [molpopgen/fwdpy11_arg_example#7]
argsimplifier uses time.time() for benchmarking progress. I think this should use [time.process_time](https://docs.python.org/3.4/library/time.html#time.process_time) instead, as this is the CPU time rather than wall-clock time.

cc. @ashander @petrelharp

**Comment by molpopgen** [comment]
This is an easy enough change to make--thanks!

**Comment by molpopgen** [comment]
Closing because #8 addresses this.
